# Generated by Django 4.2.5 on 2023-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('feedtype', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
