# Generated by Django 4.2.5 on 2023-09-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('fr', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('frday', models.CharField(max_length=5)),
                ('msg', models.CharField(max_length=150)),
            ],
        ),
    ]
