# Generated by Django 4.2.5 on 2023-09-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0002_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='frday',
        ),
    ]
