# Generated by Django 4.2.5 on 2023-09-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0003_remove_leave_frday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
