# Generated by Django 4.2.5 on 2023-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0005_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='frday',
        ),
        migrations.AlterField(
            model_name='leave',
            name='subject',
            field=models.CharField(max_length=5),
        ),
    ]
