# Generated by Django 4.2.5 on 2023-09-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0006_remove_leave_frday_alter_leave_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leave',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
