# Generated by Django 4.2.5 on 2023-09-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0007_leave_status_alter_leave_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.IntegerField(),
        ),
    ]
