# Generated by Django 4.2.5 on 2023-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empzone', '0008_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
