# Generated by Django 4.2.3 on 2023-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('salary', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('qua', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=10)),
            ],
        ),
    ]
