# Generated by Django 4.2.5 on 2023-09-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nfc',
            fields=[
                ('nfcid', models.IntegerField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
