# Generated by Django 4.2.5 on 2023-09-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0002_nfc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nfc',
        ),
    ]
