# Generated by Django 4.2.5 on 2023-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0003_delete_nfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nfc',
            fields=[
                ('nfcid', models.IntegerField(primary_key=True, serialize=False)),
                ('nfc', models.CharField(max_length=200)),
            ],
        ),
    ]
