# Generated by Django 4.2.5 on 2023-09-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0005_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
