# Generated by Django 4.2.5 on 2023-09-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0006_attend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
