# Generated by Django 4.2.5 on 2023-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0007_delete_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('salary', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
