# Generated by Django 4.2.5 on 2023-09-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0008_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='status',
            field=models.IntegerField(),
        ),
    ]
